---
title: Quinn Cantwell
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: "/projects/:path/"
  uploads:
    title: Uploads
    output: true
    permalink: "/uploads/:path/"
defaults:
- scope:
    path: ''
    type: projects
  values:
    title: 
    categories: stills
    date: 2016-09-15 12:00:00.000000000 Z
    thumbnail_image: 
    gallery:
    - file: 
    videos:
    - url: 
    layout: stills
email: quinn.cagney@gmail.com
baseurl: "/"
markdown: kramdown
description: Quinn Cantwell is a San Francisco-based video director.
theme: minima
plugins:
- jekyll-feed
video: https://player.vimeo.com/external/224967671.hd.mp4?s=d6b09aa6c2ff24d67a326f4a9fde0af7481719f9&profile_id=175
image: "/uploads/Hero_12.jpg"
about_text: |-
  Buongiorno! I am a San Francisco-based video director. I have created video and photo content for Everlane, SoulCycle, Reformation, Zegna, and Opening Ceremony.

  I partner with in-house creative and marketing teams to ideate and execute campaigns. I lead or support any aspect: writing, directing, editing, casting, and styling!
contact_text: 'I respond most quickly to emails with kitten GIF''s: quinn.cagney@gmail.com'
